language: python

python:
  - "3.3"
  - "3.4"
  
services:
  - mysql

env:
  - DB=sqlite
  - DB=mysql
#  - DB=postgres

before_install:
  - pip install codecov

install: 
  - pip install -r dsmrreader/provisioning/requirements/base.txt -r dsmrreader/provisioning/requirements/test.txt

before_script:
#  - sh -c "if [ '$DB' = 'pgsql' ]; then dropdb -U postgres --if-exists dsmrreader; fi"
#  - sh -c "if [ '$DB' = 'pgsql' ]; then createdb -U postgres dsmrreader; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysqladmin --force drop dsmrreader; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysqladmin create dsmrreader; fi"
  - sh -c "if [ '$DB' = 'sqlite' ]; then export DJANGO_SETTINGS_MODULE='dsmrreader.config.test_sqlite'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then export DJANGO_SETTINGS_MODULE='dsmrreader.config.test_mysql'; fi"

script: 
  - ./manage.py test --noinput --with-coverage

after_success:
  - codecov
