language: python

python:
  - "3.3"
  - "3.4"
  
services:
  - mysql

env:
  - DB=sqlite DJANGO_SETTINGS_MODULE='dsmrreader.config.travis.test_sqlite'
  - DB=mysql DJANGO_SETTINGS_MODULE='dsmrreader.config.travis.test_mysql'
#  - DB=postgres

before_install:
  - pip install codecov

install: 
  - pip install -r dsmrreader/provisioning/requirements/base.txt -r dsmrreader/provisioning/requirements/test.txt

before_script:
#  - sh -c "if [ '$DB' = 'pgsql' ]; then dropdb -U postgres --if-exists dsmrreader; fi"
#  - sh -c "if [ '$DB' = 'pgsql' ]; then createdb -U postgres dsmrreader; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS dsmrreader;' -u root; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysqladmin create dsmrreader; fi"

script: 
  - ./manage.py test --noinput --with-coverage

after_success:
  - codecov
