language: python

python:
  - "3.3"
  - "3.4"

before_install:
  - pip install codecov

install: 
  - pip install -r dsmrreader/provisioning/requirements/base.txt -r dsmrreader/provisioning/requirements/test.txt

script: 
  - coverage run manage.py test --settings=dsmrreader.config.test --noinput --with-coverage

after_success:
  - codecov