language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  
services:
  - postgresql
  - mysql
  
addons:
  postgresql: "9.4"

env:
  - DB=sqlite DJANGO_SETTINGS_MODULE='dsmrreader.config.travis.sqlite'
  - DB=mysql DJANGO_SETTINGS_MODULE='dsmrreader.config.travis.mysql'
  - DB=postgresql DJANGO_SETTINGS_MODULE='dsmrreader.config.travis.postgresql'

install: 
  - pip3 install -r dsmrreader/provisioning/requirements/travis.txt
  - pip3 install -r dsmrreader/provisioning/requirements/base.txt
  - pip3 install -r dsmrreader/provisioning/requirements/test.txt
  - pip3 install -r dsmrreader/provisioning/requirements/postgresql.txt
  - pip3 install -r dsmrreader/provisioning/requirements/mysql.txt
  - pip3 install codecov

before_script:
  - sh -c "if [ '$DB' = 'postgresql' ]; then dropdb -U postgres --if-exists dsmrreader; fi"
  - sh -c "if [ '$DB' = 'postgresql' ]; then createdb -U postgres dsmrreader; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'drop database IF EXISTS dsmrreader;' -u root; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysqladmin create dsmrreader; fi"

script: 
  - py.test --cov --cov-report=term
  
after_success:
  - codecov
