language: python

python:
  - "3.3"
  - "3.4"

install: 
  - pip install -r dsmrreader/provisioning/requirements/base.txt -r dsmrreader/provisioning/requirements/test.txt

script: 
  - ./manage.py test --settings=dsmrreader.config.test --noinput --with-coverage

after_success:
  - coveralls