[tool.poetry]
name = "DSMR-reader"
version = "4"
description = "DSMR-protocol reader, telegram data storage and energy consumption visualizer"
license = "Creative Commons Attribution-NonCommercial 4.0 International Public License"

authors = [
    "Dennis Siemensma"
]

readme = 'README.md'
repository = "https://github.com/dsmrreader/dsmr-reader"
homepage = "https://dsmr-reader.readthedocs.io/"


[tool.poetry.dependencies]
python = "^3.6 || ^3.7 || ^3.8 || ^3.9"

autopep8 = "^1.5"
coreapi = "^2.3"
crcmod = "^1.7"
django = "^3.1"
django-admin-rangefilter = "^0.8"
django-admin-sortable = "^2.2"
django-colorfield = "^0.4"
django-debug-toolbar = "^3.2"
django-filter = "^2.4"
django-mathfilters = "^1.0"
djangorestframework = "^3.12"
django-solo = "^1.1"
dropbox = "^11.13"
gunicorn = "^20.1"
influxdb = "^5.3"
paho-mqtt = "^1.5"
psycopg2-binary = "^2.8"
pyserial = "^3.5"
pyserial-asyncio = "^0.5"
python-dateutil = "^2.8"
python-decouple = "^3.4"
pytz = "^2021.1"
pyyaml = "^5.4"
requests = "^2.26"
urllib3 = "^1.26"


[tool.poetry.dev-dependencies]
polib = "^1.1"
pylama = "^7.7"
pytest-cov = "^2.11"
pytest-django = "^4.4"
pytest-xdist = "^2.2"
mysqlclient = "^2.0"
sphinx = "^3.5"
sphinx-autobuild = "^2021.3"
sphinx-intl = "^2.0"
sphinx-rtd-theme = "^0.5"
